### ISSUE TITLE
downloading ImageNet data

### ISSUE THREAD

**Issue by ZaraNaSha** [KamitaniLab/GenericObjectDecoding#12]
Dear all
I have a problem when downloading the image by running your matlab code.
the error is 'The server returned the status 404 with message "Not Found" in response to the request to URL http://image-net.org/download/synset?wnid=n01518878'
could you help what is the wrong with me?
Best regards,

**Comment by mitsuaki** [comment]
@zara6697 
currently, we can not download images from web-site of ImageNet.

Alternatively, we can send you a link to download images from our sever if you are in hurry.
Please send us (brainliner-admin@atr.jp) a request email.

**Comment by ZaraNaSha** [comment]
> [brainliner-admin@atr.jp](mailto:brainliner-admin@atr.jp))

thanks a lot for your help, I could download them yesterday. i close the issue.

**Comment by MalihaUCF** [comment]
Hi @mitsuaki , I ran across the same problem. However, I used the URL links and downloaded the images from the internet directly. The total images are not 1200 now as many links were broken and some images were also corrupt. I have in total 838 images for training and testing. If possible, @zara6697  could you share all the training and test images ? 

also, I discovered, that since my images are < 1200 , I might incur problem with the corresponding fMRI matlab files. Please advise. Thanks

**Comment by mitsuaki** [comment]
The request destination for the images was changed to
https://forms.gle/ujvA34948Xg49jdn9

Please send a request from above link.

**Comment by MalihaUCF** [comment]
@mitsuaki  Thank you so much :)
