### ISSUE TITLE
Stimulus_id and image_index in fMRI data

### ISSUE THREAD

**Issue by huawei-xu** [KamitaniLab/GenericObjectDecoding#17]
When I used pandas to extract training data from subject 1, I find two problem:
1. Maybe there is a little mistake about category index. As you can see, when I sorted table by image_index, there are only 4 images in the first category and 4 images in the 151th category. 
![image](https://user-images.githubusercontent.com/55091305/86564414-c3da0180-bf98-11ea-9c06-305f257e929c.png)
2. when I use tsv file to check the relationship between the training image index and the stimulus id, I find that there may be 4 images not in right order. the No.958 image in training data is the No.959 image in the tsv file and the No.1102 image in training data is the No.1103 image in the tsv file.

**Comment by ShuntaroAoki** [comment]
Thank you for the reporting.

We've fixed the category_index and image_index. in the fMRI data files available at figshare (version 5; https://figshare.com/articles/dataset/Generic_Object_Decoding/7387130).

We did't notice this error because we actually don't use the indexes in the analysis scripts.
Sorry for any inconvenience from this error.

And so sorry for the late response.

**Comment by kubrakyuz** [comment]
Hello there,

I am working with your data set in my thesis. I want to ask how can I access voxel values with dataframe like "huawei-xu" is working.
And I need to access ROI coordinate values. Can you help me with these two issues? Thank you very much in advance.
